### ISSUE TITLE
[Plan] Landing Page - UI develop

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#4]
# setting

- [ ] CAFECA-IO/isuncoin#10

# About

- [ ] CAFECA-IO/isuncoin#11
- [ ] CAFECA-IO/isuncoin#12
- [ ] CAFECA-IO/isuncoin#13
- [ ] CAFECA-IO/isuncoin#14
- [ ] CAFECA-IO/isuncoin#15
- [ ] CAFECA-IO/isuncoin#16

# Ground StarChain

- NavBar
- Footer
- [ ] CAFECA-IO/isuncoin#17
- [ ] CAFECA-IO/isuncoin#18
- [ ] CAFECA-IO/isuncoin#19
- [ ] CAFECA-IO/isuncoin#20
- [ ] CAFECA-IO/isuncoin#21

# Design

[Mockup - About](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=9-28542&t=Y28frg67ZloxKfVi-4)

[Mockup - Ground StarChain](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=19-14581&t=Y28frg67ZloxKfVi-4)
